package com.julien.mouellic.realestatemanager.domain.model

enum class Commodity(val label: String) {
    ELEVATOR("Elevator"),
    SWIMMING_POOL("Swimming Pool"),
    GARAGE("Garage"),
    PARKING_SPOT("Parking Spot"),
    GARDEN("Garden"),
    BALCONY("Balcony"),
    TERRACE("Terrace"),
    FIREPLACE("Fireplace"),
    AIR_CONDITIONING("Air Conditioning"),
    HEATING("Heating"),
    SECURITY_SYSTEM("Security System"),
    ALARM("Alarm System"),
    INTERCOM("Intercom"),
    CELLAR("Cellar"),
    LAUNDRY_ROOM("Laundry Room"),
    STORAGE_ROOM("Storage Room"),
    GYM("Gym"),
    SAUNA("Sauna"),
    PLAYGROUND("Playground"),
    ACCESSIBLE("Accessible (Handicap)"),
    INTERNET("High-Speed Internet"),
    SMART_HOME("Smart Home System"),
    PET_FRIENDLY("Pet Friendly"),
    FURNISHED("Furnished"),
    OPEN_PLAN("Open Plan"),
    MODERN_KITCHEN("Modern Kitchen"),
    VALET_PARKING("Valet Parking"),
    ROOF_DECK("Roof Deck"),
    DOORMAN("Doorman"),
    ELEVATOR_SHAFT("Elevator Shaft"),
    CINEMA_ROOM("Cinema Room"),
    WINE_CELLAR("Wine Cellar"),
    OFFICE_SPACE("Office Space"),
    GOLF_COURSE("Golf Course Access"),
    BOAT_DOCK("Boat Dock"),
    OTHER("Other")
}
